MAILSERVER_ADDRESS: 'smtp.gmail.com'
MAILSERVER_PORT: '587'
MAILSERVER_USERNAME: 'messenger@fitwit.com'
MAILSERVER_PASSWORD: 'kharoufeh'
MAILSERVER_DOMAIN: 'fitwit.com'
ADMIN_EMAIL_ADDRESS: 'info@fitwit.com'
DEFAULT_URL: 'www.fitwit.com'
DEFAULT_MAIL_FROM: 'info@fitwit.com'
DEVELOPMENT_MAIL_RECIPIENT: 'info@fitwit.com'