# -*- encoding : utf-8 -*-

OMNIAUTH_GITHUB_ID: 'd07ec76bf981a26fc937'
OMNIAUTH_GITHUB_SECRET: 'a3df9d3591a06fb716dffa908a2bd6a20e433092'

# todo when we have the main domain setup
#OMNIAUTH_GOOGLE_KEY: 'fitwit.com'
#OMNIAUTH_GOOGLE_SECRET: '8il+pvlUtwSnbkUQ/BDDy9m9'
# https://www.google.com/a/cpanel/fitwit.com/SetupOAuth

OMNIAUTH_FACEBOOK_ID: '258145227580356'
OMNIAUTH_FACEBOOK_SECRET: 'e03528aeeb51fec9fa8549e75aa3d4c4'

OMNIAUTH_TWITTER_CONSUMER_KEY: 'jGPb210i8aqALoYzVqxuLA'
OMNIAUTH_TWITTER_SECRET: 'JacjmfSxFoGIIpzpqHGXJBmguseh0KZ1X7iGsFjtqAw'

