# -*- encoding : utf-8 -*-

OMNIAUTH_OPENID: true
OMNIAUTH_GOOGLE: true
OMNIAUTH_CAPATH: "/etc/ssl/certs"
GOOGLE_PLACE_API_KEY: 'not_used_for_v3'

OMNIAUTH_TWITTER_KEY: 'jGPb210i8aqALoYzVqxuLA'
OMNIAUTH_TWITTER_SECRET: 'JacjmfSxFoGIIpzpqHGXJBmguseh0KZ1X7iGsFjtqAw'

OMNIAUTH_FACEBOOK_KEY: '243405829036398'
OMNIAUTH_FACEBOOK_SECRET: 'da5885912a0ef06f5334979259cb1121'
# access token?
# 204378432959153|2.AQAI65O3YrSnHhdL.3600.1314961200.0-500012612|Ev7z-Z9cN4TfyU__XFEfl7wjTQw

OMNIAUTH_LINKED_IN_KEY: 'v9ynrph_sBg1B_V0MyCBZgCEXZffJn2f1vIs0jR8DvDjKwTSygeiC43myFqKMWeg'
OMNIAUTH_LINKED_IN_SECRET: 'x99YDTd0uSggdP4xgzSqFK0zr-o1EhE_X3YR1fIOBUILs6HpDTvIzrcyYV_zubQl'

#OMNIAUTH_BASECAMP_ID: 'YOUR_OMNIAUTH_BASECAMP_ID'
#OMNIAUTH_BASECAMP_SECRET: 'YOUR_OMNIAUTH_BASECAMP_SECRET'

OMNIAUTH_GITHUB_ID: 'e6585d1c094816ba1028'
OMNIAUTH_GITHUB_SECRET: 'dfc122818623a76130de9bb85158160be9b548f9'
