# -*- encoding : utf-8 -*-

OMNIAUTH_GITHUB_ID: 'b47c96fec7bf343abb5c'
OMNIAUTH_GITHUB_SECRET: '7567e1ef9afb9caee87bf3b2292f006c77c25d62'

OMNIAUTH_GOOGLE_KEY: ''
OMNIAUTH_GOOGLE_SECRET: ''

OMNIAUTH_FACEBOOK_ID: '258145227580356'
OMNIAUTH_FACEBOOK_SECRET: 'e03528aeeb51fec9fa8549e75aa3d4c4'

OMNIAUTH_TWITTER_ID: ''
OMNIAUTH_TWITTER_SECRET: ''

